"""Run the conformance matrix through the Python query layer and record results.

This file is the reference the TypeScript implementation is measured against.
Regenerating it is a deliberate step: a query change that alters output shows
up as a reviewable diff here, and a TypeScript port that drifts fails the
browser conformance test.

Run with `just generate-shared`.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path
from typing import Any

from italy_dashboard import queries as q

REPO_ROOT = Path(__file__).resolve().parent.parent
SHARED = REPO_ROOT / "shared" / "conformance"

# Compare at the precision the UI actually shows. The two engines are the same
# DuckDB build, but the round trip through JSON and JavaScript numbers makes
# exact bitwise equality a brittle thing to demand.
FLOAT_DECIMALS = 4

Entry = tuple[str, int, str]


def _tracked_parquet() -> list[Path]:
    """The COMMITTED parquet snapshot, from git rather than from a glob.

    Not `queries._parquet_files()`: that globs everything on disk, which on a
    developer's checkout also picks up the untracked dbt/ingestion inputs
    (`weather_daily.parquet`, `crime_offenders.parquet`, ...). A fresh clone
    does not have those, so a digest over them is machine-specific and the
    committed reference could never reproduce anywhere else -- which is exactly
    what it is for.

    Fails loudly rather than falling back to a glob: a silent fallback would
    produce a *different* digest, i.e. the same opaque mismatch this replaced.
    """
    try:
        listing = subprocess.run(
            ["git", "ls-files", "-z", "--", "data"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError) as exc:  # pragma: no cover
        raise RuntimeError(
            "cannot list the committed parquet snapshot: this needs `git` and a "
            "checkout of the repository, because the conformance reference is "
            "defined against the COMMITTED data, not whatever is on disk"
        ) from exc
    paths = sorted(REPO_ROOT / name for name in listing.split("\0") if name.endswith(".parquet"))
    missing = [p for p in paths if not p.is_file()]
    if missing:
        raise FileNotFoundError(
            f"committed parquet missing from the working tree: {missing}. "
            "The conformance reference cannot be generated without it."
        )
    return paths


def tracked_snapshot_fingerprint() -> tuple[Entry, ...]:
    """(repo-relative path, size, content hash) per committed parquet, sorted.

    Deliberately NOT `queries._snapshot_fingerprint()`, which serves a
    different purpose: that one busts the in-process query cache when a
    developer regenerates data, so it wants cheap change detection and uses
    absolute paths plus `st_mtime_ns`. Both of those, and the glob over
    untracked files above, make a digest that differs between two checkouts of
    the SAME commit -- so the recorded reference was unreproducible on a fresh
    clone or a git worktree (measured: 18 files here, 14 in a clone). Content
    hashing costs a few hundred ms once per regeneration and buys a digest that
    depends only on committed bytes.
    """
    entries: list[Entry] = []
    for path in _tracked_parquet():
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        entries.append((path.relative_to(REPO_ROOT).as_posix(), path.stat().st_size, digest))
    return tuple(entries)


def fingerprint_digest(fingerprint: tuple[Entry, ...]) -> str:
    """A short stable digest of the parquet snapshot the results came from."""
    payload = json.dumps([list(entry) for entry in fingerprint])
    return hashlib.sha256(payload.encode()).hexdigest()[:16]


def _normalise(value: Any) -> Any:
    """Round floats and make tuples lists, so JSON round-trips comparably."""
    if isinstance(value, float):
        return round(value, FLOAT_DECIMALS)
    if isinstance(value, dict):
        return {k: _normalise(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_normalise(v) for v in value]
    return value


def _coerce_arg(arg: Any) -> Any:
    """A two-element list naming a mart becomes the tuple the API expects."""
    if isinstance(arg, list) and len(arg) == 2 and isinstance(arg[1], list):
        return (arg[0], list(arg[1]))
    return arg


def run_case(case: dict) -> Any:
    fn = getattr(q, case["function"])
    return _normalise(fn(*[_coerce_arg(a) for a in case["args"]]))


def build() -> str:
    cases = json.loads((SHARED / "cases.json").read_text())
    results = {case["id"]: run_case(case) for case in cases}
    payload = {
        "_comment": (
            "Generated by scripts/generate_conformance_expected.py. Do not edit by "
            "hand. Regenerate with `just generate-shared` and review the diff: a "
            "change here means a query's output changed."
        ),
        "float_decimals": FLOAT_DECIMALS,
        "fingerprint": fingerprint_digest(tracked_snapshot_fingerprint()),
        "results": results,
    }
    return json.dumps(payload, indent=2, sort_keys=True, default=str) + "\n"


def main() -> int:
    SHARED.mkdir(parents=True, exist_ok=True)
    (SHARED / "expected.json").write_text(build())
    cases = json.loads((SHARED / "cases.json").read_text())
    print(f"wrote {SHARED / 'expected.json'} ({len(cases)} cases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
