"""Generate the shared palette artifacts from italy_dashboard/palette.py.

palette.py stays the single source of truth: it is what the colour validator
checks and what the golden tests pin. This script projects it into formats the
static frontend can consume, and a test asserts the committed output matches,
so a palette edit that skips regeneration fails the build rather than giving
the two frontends different colours.

Run with `just generate-shared`.
"""

from __future__ import annotations

import json
from pathlib import Path

from italy_dashboard import palette

SHARED = Path(__file__).resolve().parent.parent / "shared"

HEADER = "Generated by scripts/generate_palette.py from italy_dashboard/palette.py."
EDIT_WARNING = "Do not edit by hand: a test asserts this matches the generator."


def build_json() -> str:
    """The palette as JSON, with a trailing newline."""
    data = {
        "_comment": f"{HEADER} {EDIT_WARNING}",
        "surface": {"light": palette.SURFACE_LIGHT, "dark": palette.SURFACE_DARK},
        "page_bg": {"light": palette.PAGE_BG_LIGHT, "dark": palette.PAGE_BG_DARK},
        "border": {"light": palette.BORDER_LIGHT, "dark": palette.BORDER_DARK},
        "axis": {"light": palette.AXIS_LIGHT, "dark": palette.AXIS_DARK},
        "ink_primary": {"light": palette.INK_PRIMARY_LIGHT, "dark": palette.INK_PRIMARY_DARK},
        "ink_secondary": {
            "light": palette.INK_SECONDARY_LIGHT,
            "dark": palette.INK_SECONDARY_DARK,
        },
        "ink_muted": {"light": palette.INK_MUTED_LIGHT, "dark": palette.INK_MUTED_DARK},
        "gridline": {"light": palette.GRIDLINE_LIGHT, "dark": palette.GRIDLINE_DARK},
        "warning": {"light": palette.WARNING_LIGHT, "dark": palette.WARNING_DARK},
        "categorical": {
            "light": list(palette.CATEGORICAL_LIGHT),
            "dark": list(palette.CATEGORICAL_DARK),
        },
        "diverging": {
            "light": list(palette.DIVERGING_LIGHT),
            "dark": list(palette.DIVERGING_DARK),
        },
        "sequential": {
            "light": list(palette.SEQUENTIAL_LIGHT),
            "dark": list(palette.SEQUENTIAL_DARK),
        },
    }
    return json.dumps(data, indent=2) + "\n"


def build_css() -> str:
    """The diverging ramp as CSS custom properties, all three colour-mode states.

    Delegates the body to `palette.diverging_css_vars()` rather than
    re-deriving it: that function is what the Reflex app injects inline, and
    duplicating its selector logic here is exactly how the two could drift
    (see its docstring for why `.dark`, `[data-theme="dark"]` and a guarded
    `prefers-color-scheme` media query are all three needed).
    """
    return f"/* {HEADER} */\n/* {EDIT_WARNING} */\n\n{palette.diverging_css_vars()}"


def main() -> int:
    SHARED.mkdir(parents=True, exist_ok=True)
    (SHARED / "palette.json").write_text(build_json())
    (SHARED / "palette.css").write_text(build_css())
    print(f"wrote {SHARED / 'palette.json'} and {SHARED / 'palette.css'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
