"""Generate the shared palette artifacts from italy_dashboard/palette.py.

palette.py stays the single source of truth: it is what the colour validator
checks and what the golden tests pin. This script projects it into formats the
static frontend can consume, and a test asserts the committed output matches,
so a palette edit that skips regeneration fails the build rather than giving
the two frontends different colours.

Run with `just generate-shared`.
"""

from __future__ import annotations

import json
from pathlib import Path

from italy_dashboard import palette

SHARED = Path(__file__).resolve().parent.parent / "shared"

HEADER = "Generated by scripts/generate_palette.py from italy_dashboard/palette.py."
EDIT_WARNING = "Do not edit by hand: a test asserts this matches the generator."


def build_json() -> str:
    """The palette as JSON, with a trailing newline."""
    data = {
        "_comment": f"{HEADER} {EDIT_WARNING}",
        "surface": {"light": palette.SURFACE_LIGHT, "dark": palette.SURFACE_DARK},
        "categorical": {
            "light": list(palette.CATEGORICAL_LIGHT),
            "dark": list(palette.CATEGORICAL_DARK),
        },
        "diverging": {
            "light": list(palette.DIVERGING_LIGHT),
            "dark": list(palette.DIVERGING_DARK),
        },
        "sequential": {
            "light": list(palette.SEQUENTIAL_LIGHT),
            "dark": list(palette.SEQUENTIAL_DARK),
        },
    }
    return json.dumps(data, indent=2) + "\n"


def build_css() -> str:
    """The diverging ramp as CSS custom properties, both modes.

    Deliberately identical in property names and values to what
    `palette.diverging_css_vars()` injects into the Reflex app, so the warming
    stripes resolve to the same colours on both sites.
    """
    lines = [f"/* {HEADER} */", f"/* {EDIT_WARNING} */", ""]
    lines.append(":root {")
    for i, colour in enumerate(palette.DIVERGING_LIGHT):
        lines.append(f"  --div-{i}: {colour};")
    lines.append("}")
    lines.append("")
    lines.append(".dark {")
    for i, colour in enumerate(palette.DIVERGING_DARK):
        lines.append(f"  --div-{i}: {colour};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    SHARED.mkdir(parents=True, exist_ok=True)
    (SHARED / "palette.json").write_text(build_json())
    (SHARED / "palette.css").write_text(build_css())
    print(f"wrote {SHARED / 'palette.json'} and {SHARED / 'palette.css'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
