"""Run the conformance matrix through the Python query layer and record results.

This file is the reference the TypeScript implementation is measured against.
Regenerating it is a deliberate step: a query change that alters output shows
up as a reviewable diff here, and a TypeScript port that drifts fails the
browser conformance test.

Run with `just generate-shared`.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from italy_dashboard import queries as q

SHARED = Path(__file__).resolve().parent.parent / "shared" / "conformance"

# Compare at the precision the UI actually shows. The two engines are the same
# DuckDB build, but the round trip through JSON and JavaScript numbers makes
# exact bitwise equality a brittle thing to demand.
FLOAT_DECIMALS = 4


def fingerprint_digest(fingerprint: tuple) -> str:
    """A short stable digest of the parquet snapshot the results came from."""
    payload = json.dumps([[str(p), size, mtime] for p, size, mtime in fingerprint])
    return hashlib.sha256(payload.encode()).hexdigest()[:16]


def _normalise(value: Any) -> Any:
    """Round floats and make tuples lists, so JSON round-trips comparably."""
    if isinstance(value, float):
        return round(value, FLOAT_DECIMALS)
    if isinstance(value, dict):
        return {k: _normalise(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_normalise(v) for v in value]
    return value


def _coerce_arg(arg: Any) -> Any:
    """A two-element list naming a mart becomes the tuple the API expects."""
    if isinstance(arg, list) and len(arg) == 2 and isinstance(arg[1], list):
        return (arg[0], list(arg[1]))
    return arg


def run_case(case: dict) -> Any:
    fn = getattr(q, case["function"])
    return _normalise(fn(*[_coerce_arg(a) for a in case["args"]]))


def build() -> str:
    cases = json.loads((SHARED / "cases.json").read_text())
    results = {case["id"]: run_case(case) for case in cases}
    payload = {
        "_comment": (
            "Generated by scripts/generate_conformance_expected.py. Do not edit by "
            "hand. Regenerate with `just generate-shared` and review the diff: a "
            "change here means a query's output changed."
        ),
        "float_decimals": FLOAT_DECIMALS,
        "fingerprint": fingerprint_digest(q._snapshot_fingerprint()),
        "results": results,
    }
    return json.dumps(payload, indent=2, sort_keys=True, default=str) + "\n"


def main() -> int:
    SHARED.mkdir(parents=True, exist_ok=True)
    (SHARED / "expected.json").write_text(build())
    cases = json.loads((SHARED / "cases.json").read_text())
    print(f"wrote {SHARED / 'expected.json'} ({len(cases)} cases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
